---
- name: Wait for control-plane API
  wait_for:
    host: "{{ groups['master'][0] }}"
    port: 6443
    timeout: 600

- name: Get fresh join command from master
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  command: kubeadm token create --ttl 2h --print-join-command
  register: join_cmd

- name: Join the cluster
  shell: "{{ join_cmd.stdout }} --ignore-preflight-errors=all"
  args:
    creates: /etc/kubernetes/kubelet.conf
