---
- name: Determine master private IP
  set_fact:
    master_ip: "{{ ansible_default_ipv4.address }}"

- name: kubeadm init (idempotent, with CRI socket)
  command: >
    kubeadm init
    --apiserver-advertise-address={{ master_ip }}
    --pod-network-cidr={{ pod_cidr }}
    --cri-socket=unix:///run/containerd/containerd.sock
  args:
    creates: /etc/kubernetes/admin.conf

- name: Pause after kubeadm init
  pause:
    seconds: "{{ pause_medium | default(20) }}"

- name: Setup kubeconfig for admin user
  become_user: "{{ ansible_user | default('azureuser') }}"
  shell: |
    mkdir -p $HOME/.kube
    sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
    sudo chown -R {{ ansible_user | default('azureuser') }}:{{ ansible_user | default('azureuser') }} $HOME/.kube
  changed_when: false

# Calico
- name: Download Calico manifest
  get_url:
    url: "https://raw.githubusercontent.com/projectcalico/calico/{{ calico_version }}/manifests/calico.yaml"
    dest: /root/calico.yaml
    mode: '0644'

- name: Align Calico pod CIDR if needed
  replace:
    path: /root/calico.yaml
    regexp: '192\.168\.0\.0/16'
    replace: "{{ pod_cidr }}"

- name: Apply Calico CNI (with retries)
  shell: "KUBECONFIG=/etc/kubernetes/admin.conf kubectl apply -f /root/calico.yaml"
  register: calico_apply
  retries: 5
  delay: 10
  until: calico_apply.rc == 0

- name: Pause to let Calico bootstrap
  pause:
    seconds: "{{ pause_medium | default(20) }}"

- name: Generate join command (2h TTL)
  command: kubeadm token create --ttl 2h --print-join-command
  register: join_cmd

- name: Save join command on master
  copy:
    dest: /root/join.sh
    content: |
      #!/usr/bin/env bash
      set -e
      {{ join_cmd.stdout }} --cri-socket=unix:///run/containerd/containerd.sock --ignore-preflight-errors=all
    mode: '0750'

