---
# Repo Kubernetes (pkgs.k8s.io)
k8s_version_repo: "v1.30"

# Calico (manifests)
calico_version: "v3.27.3"

# Pod CIDR (peut être surchargé par --extra-vars pod_cidr=...)
pod_cidr: "192.168.0.0/16"

# Pauses confort
pause_short: 10
pause_medium: 20

# Forcer l'interpréteur Python si besoin
ansible_python_interpreter: /usr/bin/python3

