apiVersion: v1
kind: Namespace
metadata:
  name: web-kubectl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: web-kubectl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        # On écrase la page d'accueil avec notre message
        command: ["/bin/sh", "-c"]
        args:
          - echo '<h1>Bienvenue sur mon Nginx déployé via Kubernetes 🚀</h1>' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: web-kubectl
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30180

